name: Repo Sync

on:
  schedule:
    # Every 3 hours
    - cron: '0 */1 * * *'
  # Allow the action to be manually run
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          base: main
          head: main
