name: Repo Sync

on:
  schedule:
    # Every 3 hours
    - cron: '0 */1 * * *'
  # Allow the action to be manually run
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref:  main
          
      - id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: GoogleChrome/developer.chrome.com
      
      - if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."
    
      - if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."
      
      - run: echo ${{ steps.sync.outputs.has_new_commits }}
          
          

